name: leon gottheim
favicon: null
layout_spectrum: 0.8441876608412713
typography_spectrum: 0.5982088376767933
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.878601387841627
  lightness: 0.34194895275868475
  saturation: 0.3154154010117054
  rhythmicContrast: 0.016223692568019032
purpose: []
